### ISSUE TITLE
error log need more details

### ISSUE THREAD

**Issue by Brothers3398** [Sinflower/WolfTL#1]
1.need filename
![image](https://github.com/user-attachments/assets/b7be03f1-edcf-48a9-8784-285598404e4a)

Patching CommonEvents ... [json.exception.parse_error.101] parse error at line 7260, column 44: syntax error while parsing value - invalid string: forbidden character after backslash; last read: '"@1\n誘
-it is explained in the error log, but it would be much easier to find if the file name was added
-can error log output support UTF-8?

2.unknow error
![image](https://github.com/user-attachments/assets/874bd197-a78e-4c93-bb8d-00a0e07918c6)
[Database.h:241 - Data::Patch()] Data field name mismatch
i figured it out that all the names in the DB should be unified, 
but don't know which name is the problem and what line number is the error with filename

**Comment by Sinflower** [comment]
Thanks for the feedback; I will see to it that the required information is added.

**Comment by Brothers3398** [comment]
i can't find what problem have CDataBase.json cannot make injected data
DB and SYSDB are fine, but I don't know what's wrong with CDB file
if use an orignal CDB file, it will be injected normally

[wolfTL-data.zip](https://github.com/user-attachments/files/16490809/wolfTL-data.zip)
here is data i trying it

wolfrpg ver is 3.382

**Comment by Sinflower** [comment]
You are missing a space "`　`" in line 70641, it should be:
`"name": "　… 이하 생략",`

I had to use a debugger to actually find that problem, and it highlights the need for better error messages. As for the UTF-8 support, well, that's more of a Windows Problem, but I will see what I can do; in the worst case, I will just write a proper log file containing the text.

**Comment by Brothers3398** [comment]
> You are missing a space "`　`" in line 70641, it should be: `"name": "　… 이하 생략",`
![image](https://github.com/user-attachments/assets/6b26972f-3402-4dbf-bf21-e5d735d7dc7a)
thank you for letting me know that. game/editor work well.
 
> As for the UTF-8 support, well, that's more of a Windows Problem, but I will see what I can do; in the worst case, I will just write a proper log file containing the text.
i think it would be good to choose command line

thanks

**Comment by Brothers3398** [comment]
> You are missing a space "`　`" in line 70641, it should be: `"name": "　… 이하 생략",`
> 
> I had to use a debugger to actually find that problem, and it highlights the need for better error messages. As for the UTF-8 support, well, that's more of a Windows Problem, but I will see what I can do; in the worst case, I will just write a proper log file containing the text.

![image](https://github.com/user-attachments/assets/3f2da00c-eebc-4c40-a787-cfcff3e6f5e0)

i tested wolfTL 0.41
error log is much more detailed than last time, making it easier to fix. thank you
