### ISSUE TITLE
extract Game.dat

### ISSUE THREAD

**Issue by zechs-boop** [Sinflower/WolfTL#2]
Is it possible to extract Game.dat?
I want to change the font and title

**Comment by Sinflower** [comment]
Hi,
extraction and modification of Game.dat is currently disabled as it tends to fail and cause the game to break. I will be looking into this in the future, but for now the only way to change the font and title is by using the editor.

**Comment by zechs-boop** [comment]
game.dat in the pro version is encrypted, so I couldn't modify it even when opening it with a hex editor.
Thank you for your reply.
